### PR TITLE
sync with upstream v5.0 and react to breaking webpack5 changes

### PR DESCRIPTION
**Pull request by aruniverse**
Only files that had conflicts:

- packages\react-scripts\package.json
- packages\react-scripts\config\webpack.config.js
- packages\react-scripts\config\webpackDevServer.config.js
- packages\react-scripts\scripts\utils\createJestConfig.js
- packages\react-scripts\scripts\build.js

Diff between upstream and our imjs fork: https://github.com/imodeljs/create-react-app/compare/master...imodeljs:cra5
Diff between our cra fork 4.x and 5.0 (this pr): https://github.com/imodeljs/create-react-app/compare/4.x...imodeljs:cra5

### CODE REVIEW

**Review by MichaelBelousov — APPROVED** [review]
I only really went through the diff with 4.x deeply, but LGTM if it runs on your machine. Would be nice if we had a sanity check script using display-test-app or something.

**Comment by calebmshafer** [comment]
@aruniverse did you update master of our fork?

**Comment by aruniverse** [comment]
> @aruniverse did you update master of our fork?

I last synced it with upstream 5.0.1 release, its behind a few commits now, but they havent published a new release. Ive typically been trying to keep master in sync with their releases

**Comment by calebmshafer** [comment]
> > @aruniverse did you update master of our fork?
> 
> I last synced it with upstream 5.0.1 release, its behind a few commits now, but they havent published a new release. Ive typically been trying to keep master in sync with their releases

@aruniverse okay, that sounds good. Yea definitely keep it with the last release instead of completely riding the tip.

**Review by calebmshafer — APPROVED** [review]

**Pull request merged**
