### PR TITLE
Merge with facebook/create-react-app/master

### PR DESCRIPTION
**Pull request by calebmshafer**
This the first time we're doing a merge from upstream so I wanted to layout the process I followed and I'll add it to our README if we all agree it's the right way to go.

1. Push upstream `master` to imodeljs `master`, there should _never_ be any conflicts. (needs to be pushed by an admin but we should automate this at some point...)
   ```sh
   git remote add upstream https://github.com/facebook/create-react-app.git
   git fetch upstream
   git checkout master
   git merge upstream/master
   git push
   ```
1. Update `imodeljs` branch with new imodeljs `master`
   a.
     ```sh
     git checkout imodeljs
     git checkout -b merge-with-master
     git merge origin/master
     ```
   b. Resolve merge conflicts
   c. Set the version of react-scripts to `-dev.0` of whatever is incoming from `master`
   c. Commit, push and open PR

The main reason I wanted to create a PR branch is to have a linear first-parent history for all explicit changes to our branch instead of directly pushing overtop of them all. That way it's an explicit merge commit instead of a fast-forward merge.  Let me know what you think.

### CODE REVIEW

**Comment by aruniverse** [comment]
I think the steps you've defined above is accurate and is what i was doing earlier on. We can probably set a chron job for pushing updates from upstream to master. How are you going to get around the issue above with the CLA? Do we want to setup a release pipeline for the dev builds of this before it gets merged in?

**Comment by calebmshafer** [comment]
> I think the steps you've defined above is accurate and is what i was doing earlier on. We can probably set a chron job for pushing updates from upstream to master. How are you going to get around the issue above with the CLA? Do we want to setup a release pipeline for the dev builds of this before it gets merged in?

I disabled CLA Assistant for this entire repo so that issue should be resolved for all future PRs.  In terms of a dev release, yes I'd like to get one out so that we can start testing it.  Let's wait to merge this into our branch until we're ready though, I guess that means releasing the -dev version from this PR.  I'll get around to that after #9.

Also, at @wgoehrig's suggestion I'll probably update those steps to require updating `master` to the latest react-scripts git tag in the `facebook/create-react-scripts` repo.  Still haven't figured out where they released the package from since it does show up on npmjs but just not directly on `master`.

**Comment by aruniverse** [comment]
> Also, at @wgoehrig's suggestion I'll probably update those steps to require updating `master` to the latest react-scripts git tag in the `facebook/create-react-scripts` repo. Still haven't figured out where they released the package from since it does show up on npmjs but just not directly on `master`.

I didnt see an issue or pr branch where they did the release off of. Dan abramov mightve just done it himself locally. https://github.com/facebook/create-react-app/pull/9470

**Comment by calebmshafer** [comment]
Closing this in favor of #22

**Pull request closed without merging**
